source <(antibody init)
antibody bundle < $XDG_CONFIG_HOME/antibody/zsh_plugins.txt
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh
autoload -U colors && colors
autoload -Uz compinit
[ -f $XDG_CACHE_HOME/zcompdump ] && compinit -d $XDG_CACHE_HOME/zcompdump || compinit -C -d $XDG_CACHE_HOME/zcompdump

setopt correct                        # Auto correct mistakes
setopt extendedglob                   # Extended globbing. Allows using regular expressions with *
setopt nocaseglob                     # Case insensitive globbing
setopt rcexpandparam                  # Array expension with parameters
setopt nocheckjobs                    # Don't warn about running processes when exiting
setopt numericglobsort                # Sort filenames numerically when it makes sense
setopt nobeep                         # No beep
setopt appendhistory                  # Immediately append history instead of overwriting
setopt histignorealldups              # If a new command is a duplicate, remove the older one
setopt autocd                         # if only directory path is entered, cd there.
setopt prompt_subst                   # enable substitution for prompt

HISTFILE=$XDG_DATA_HOME/zsh/history
HISTSIZE=1000
SAVEHIST=500
WORDCHARS=${WORDCHARS//\/[&.;]}       # Don't consider certain characters part of the word

zstyle ':completion:*' matcher-list '' \
  'm:{a-z\-}={A-Z\_}' \
  'r:[^[:alpha:]]||[[:alpha:]]=** r:|=* m:{a-z\-}={A-Z\_}' \
  'r:|?=** m:{a-z\-}={A-Z\_}'

local ret_status="%(?:%{$fg_bold[green]%}λ:%{$fg_bold[red]%}λ)"
PROMPT='${ret_status} %{$fg[cyan]%}%c%{$reset_color%} '
[ -f $XDG_CONFIG_HOME/zsh/prompt ] && source $XDG_CONFIG_HOME/zsh/prompt

alias cp='cp -iv'
alias df='df -h'
alias free='free -m'
alias l='ls -la --color=tty'
alias ls='ls --color=tty'
alias ga='git add'
alias gcmsg='git commit -m'
alias gpu='git push'
alias gsb='git status -b'
alias glog='git log'
alias gdiff='git diff'
alias ln='ln -v'
alias chmod='chmod -c'
alias chown='chown -c'
alias mkdir='mkdir -v'
alias mv='mv -iv'
alias rm='rm -v'
alias cp='cp -iv'
alias rsync='rsync -avP'
alias um='udiskie-umount -a'
alias yay='yay --color=auto'
alias pacman='pacman --color=auto'
alias fucking='sudo'
alias motherfucking='sudo'
alias fcking='sudo'
alias f='ranger'
alias e='nvim'
alias ydm='youtube-dl -x -f bestaudio --audio-format vorbis'
alias evpc='expressvpn connect'
alias evpd='expressvpn disconnect'
alias evps='expressvpn status'
alias tsm='transmission-remote'
alias pr='pipenv run python'
