#!/bin/sh

capacity=$(cat /sys/class/power_supply/"$1"/capacity) || exit
status=$(cat /sys/class/power_supply/"$1"/status)

if [ "$capacity" -ge 50 ]; then
	color="#de935f"
else
	color="#cc6666"
fi

[ "$status" = "Charging" ] && color="#8c9440"

echo "<span color='$color'>$status $capacity%</span>" | sed -e "s/Discharging/dis/g;s/Charging/chr/g"
