#!/bin/sh

capacity=$(cat /sys/class/power_supply/BAT0/capacity) || exit
status=$(cat /sys/class/power_supply/BAT0/status)

batstatus="$status $capacity%"

if [ "$status" -lt 25 ]; then
    batstatus="<span color=\"#cc6666\">$status $capacity%</span>"
fi

echo "$batstatus" | sed -e "s/Discharging/dischr/g;s/Charging/chr/g"
