#!/bin/sh

filter() {
	sed "/^volume:/d" | tac | sed -e "s/\\&/&amp;/g;s/\\[paused\\].*/<span color=\"gray\" font_style=\"italic\">/g;s/\\[playing\\].*/<span>/g" | tr -d '\n' | sed -e "s/$/<\\/span>/g"
	}

case $BLOCK_BUTTON in
    1) mpc prev   | filter ;;
    2) mpc toggle | filter ;;
    3) mpc next   | filter ;;
    4) mpc seek +1% | filter ;;
    5) mpc seek -1% | filter ;;
    *) mpc status | filter ;;
esac; exit
