#!/bin/sh

artist=$(playerctl metadata artist 2>&1)
if [ "$artist" = "No players found" ]; then
    exit
fi

title=$(playerctl metadata title)

echo "$artist - $title"

case $BLOCK_BUTTON in
    1) playerctl previous ;;
    2) playerctl play-pause ;;
    3) playerctl next ;;
esac
