#!/bin/sh

format() {
    playerstatus=$(playerctl status)
    artist=$(playerctl metadata artist)
    title=$(playerctl metadata title)

    [ -z "$playerstatus" ] && exit
    echo "$playerstatus$artist - $title" | sed -e "s/Paused/<span color=\"gray\" font_style=\"italic\">/g;s/Playing/<span>/g" | sed -e "s/$/<\/span>/g"
}

case $BLOCK_BUTTON in
    1) playerctl previous | format ;;
    2) playerctl play-pause | format ;;
    3) playerctl next | format ;;
    *) format;;
esac; exit
