#!/bin/sh

case $BLOCK_BUTTON in
	3) pulsemixer --toggle-mute ;;
	4) pulsemixer --change-volume +1 ;;
	5) pulsemixer --change-volume -1 ;;
esac

[ "$(pulsemixer --get-mute)" = "1" ] && printf "<span color=\"gray\" font_style=\"italic\">MUTE</span>" && exit

vol=$(pulsemixer --get-volume | awk '{print $1}')

echo "$vol%" && exit
