. ~/.xprofile

# Default dwm colors
# ssh-agent dwm -sb "#005577" -nb "#222222" -sfg "#bbbbbb" -sbg "#222222" -tsfg "#eeeeee" -tsbg "#005577" -tnfg "#bbbbbb" -tnbg "#222222" -isfg "#eeeeee" -isbg "#005577" -infg "#bbbbbb" -inbg "#222222"

ssh-agent dwm
